### ISSUE TITLE
Add user removal/group membership options

### ISSUE THREAD

**Issue by syntaxerrormmm** [bglug-it/nethserver-usercsvimport#1]
I think it could be useful to have the following options in the script:
- User removal: takes the first field in CSV and removes the corresponding user. We should warn the script user that data will be lost. Also, we should warn the user when a username is not found;
- Group membership: the script should allow to removal of the membership of a group (or, better, assure that he/she isn't member of the group).

**Comment by paspo** [comment]
In my opinion (as a professional :) ) we should do this in a smart way:
- User removal: if a line starts with a "-" (dash) then the user is deleted and the rest of the line is skipped
- Group membership: if a user has some groups assigned which starts with a '-' then we remove this user from that group

It's better to have also a parameter to enable these "deletions".

**Comment by syntaxerrormmm** [comment]
Like your ideas, though we should think of the following scenario:
- Someone creates the "freshmen" file, saves it somewhere and use it to create new users in bulk;
- Years pass;
- Someone in charge of cleaning up takes the original file to "revert" the creation operation (thus deleting the creation of users/groups).

I would like to leave the file as-is, without doing any modification at all. We may choose to save the file (internally with the import utility) after a successful importation, just to have a sure copy to revert the creation task.

This has obviously to be locked down to notify the user for dangerous operations, but that's why I have though of a single switch parameter to do that and a serie of notifications.

**Comment by paspo** [comment]
I'm kinda OK with user deletion: with a dedicated parameter, we parse the same list and we delete users instead of creating them.
BTW, a common scenario is a user "migrating" from a group to another. We still need a way to manage that.
